feat: optimize performance; tag filter for translator; localization. …
zotero-chinese/website pull request #51
Opened 2024-06-12 09:52 UTC by jiaojiaodubai

…fix: some fields value overflow in translatorCard/translatorDetail

2024-06-12 10:14 UTC, northword commented
![Screenshot_2024-06-12-18-14-06-737_com.microsoft.emmx.jpg](https://github.com/zotero-chinese/website/assets/44738481/57d2b3a8-7e2a-4630-b632-6c049dfad7d1)

https://vitepress.dev/zh/guide/routing#dynamic-routes

如何理解这段？

2024-06-12 11:16 UTC, jiaojiaodubai commented
> 如何理解这段？

- **传递给页面的参数**：特指 `params`，即 `*.path.ts` 中由 `path()` 在构建时分配的数据；
- **JavaScript Payload**：JS的负载，也就是页面中嵌入的 `<script>` 内的数据，浏览器访问 URL -> 请求 Document -> 加载其中的 JS。
- **序列化**：从易于传输的格式到可操作的格式，即通过 `JSON.parse()` 将负载中的 string 读出为 object。

总之，这段话的意思应该是：Markdown 或 HTML 的内容如果用 `params` 传输，就会按部就班走 `JSON.parse()` ，这就比较费劲；应该写到 `content` 里面，让浏览器自己去解析。

2024-06-12 11:26 UTC, northword requested changes
另外，项目使用 prettier 来 format code，请保持使用 prettier ，可以运行 `lint:prettier`。

如果使用 vscode-prettier，请确保所有配置项都处于默认状态。

2024-06-12 11:26 UTC, northword commented on src/translators/components/TranslatorDetails.vue
> +                <div v-else-if="field === 'tags'" class="tags-container">
对比度太低了，是否可以换为 premier？
![image](https://github.com/zotero-chinese/website/assets/44738481/a3761119-4e33-4fb6-b9b5-17bd3d702e15)

2024-06-12 11:26 UTC, northword commented on src/translators/components/TranslatorDetails.vue
> +                    <img src="..\..\wiki\assets\icons\item-type\note.svg" class="attachment-icon" />
可以包在 al-icon 里：https://element-plus.org/zh-CN/component/icon.html#%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8-svg-%E5%9B%BE%E6%A0%87

2024-06-12 11:26 UTC, northword commented on src/translators/composables/localize.ts
按照 Vue 3 的推荐，应使用 `useXxx` 作为组合式函数的前缀

2024-06-12 11:26 UTC, northword commented on src/translators/data/translatorsLittle.data.ts
> +import { getTranslatorType, getItemType } from "../composables/localize";
我觉得最好不要在 node 侧调用 client 的方法，

这个本地化要么在 node 侧全部完成，要么全部在 client 完成，不要一部分在 client 实现，一部分在 node 侧实现

2024-06-12 11:55 UTC, jiaojiaodubai commented on src/translators/components/TranslatorDetails.vue
> +    <el-descriptions-item label="ID" :span="2" label-class-name="fieldLabel">
加了 scope 后就不起效了，暂时没找到原因，其它样式可能也受到影响，但合理的做法确实应该隔离。

2024-06-12 11:58 UTC, northword commented on src/translators/components/TranslatorDetails.vue
> +    <el-descriptions-item label="ID" :span="2" label-class-name="fieldLabel">
是否需要 ::deep() ？

https://cn.vuejs.org/api/sfc-css-features.html#deep-selectors

2024-06-12 11:59 UTC, northword commented on src/translators/components/TranslatorDetails.vue
> +    <el-descriptions-item label="ID" :span="2" label-class-name="fieldLabel">
https://element-plus.org/zh-CN/component/descriptions.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
![image](https://github.com/zotero-chinese/website/assets/44738481/5948f2e4-8c70-4d1d-b96f-a4e90f661a88)

2024-06-12 12:04 UTC, northword commented on src/translators/components/TranslatorDetails.vue
> +                <div v-else-if="field === 'tags'" class="tags-container">
> premier 用在整体灰黑的 Detail 页面似乎过于突出了 

那就保持现有的吧

2024-06-12 12:20 UTC, jiaojiaodubai commented on src/translators/components/TranslatorDetails.vue
> +      <template v-if="testCase.type === 'web'"><a :href="testCase.url">{{ testCase.url }}</a></template>
暂时放在“条目 i”里面了，放标题可能更好，但标题并不是一个稳定的字段

2024-06-12 12:27 UTC, jiaojiaodubai commented on src/translators/components/TranslatorDetails.vue
> +                    <img src="..\..\wiki\assets\icons\item-type\note.svg" class="attachment-icon" />
包装后支持改变[颜色和大小](https://element-plus.org/zh-CN/component/icon.html#attributes)（也许还能防止溢出），但并不能解决图标和文字的间距问题。

2024-06-12 13:12 UTC, jiaojiaodubai commented on src/translators/data/translatorsLittle.data.ts
> +import { getTranslatorType, getItemType } from "../composables/localize";
参考 vitePress 的做法，统一到 client 实现。

2024-06-13 00:44 UTC, northword commented on src/components.d.ts
> +    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
重新build一次移除这一行

2024-06-13 01:01 UTC, northword requested changes
我最早要明天下午才能继续处理了，要开组会了

2024-06-13 01:01 UTC, northword commented on src/translators/types/index.d.ts
> +  translatorType: number;
这个可以写到上一行的pick里

2024-06-13 02:51 UTC, jiaojiaodubai commented on src/translators/components/TranslatorCard.vue
> +            type="info"
因为 `translator.translatorType` 是一个 `number`，而经过处理之后才是数组。

2024-06-13 06:24 UTC, jiaojiaodubai commented on src/translators/components/TranslatorCard.vue
> +function sortedTypes(itemTypes: Array<string>) {
修改为在 <script> 中提前定义常量。

2024-06-13 06:24 UTC, jiaojiaodubai commented on src/translators/components/TranslatorCard.vue
> +            type="info"
修改为在 <script> 中提前定义常量。

2024-06-14 05:17 UTC, northword approved these changes
修改了一些。

后面可能需要在项目中引入 Tailwind CSS 了。

---

如果你没有其他的问题，我们就合并这个 PR。

2024-06-14 05:22 UTC, northword commented on src/translators/components/TranslatorCard.vue
> +            type="info"
我个人倾向把需要遍历的值先创建出来；

另外，对于 sorted 那个方法，我修改成了直接用原始值比较，这样可以减少一次从原始值查找中文的步骤。

2024-06-14 05:23 UTC, jiaojiaodubai commented
我觉得有一些更改违背了初始的意图

2024-06-14 05:26 UTC, northword commented
> 我觉得有一些更改违背了初始的意图

比如？

2024-06-14 05:34 UTC, jiaojiaodubai commented on src/translators/components/TranslatorCard.vue
> +            type="info"
提前创建出来可能有两个问题：

1. 被遍历的东西只是创建元素的时候供索引，之后再也不会访问它，如果写为 script 中的常量，则这个常量始终存在，带来额外的消耗（虽然这个消耗可能微乎其微）。
2. 从可读性的角度来说，对于这些只使用一次的变量，在不同的地方定义和应用变量，弱化了关联性，阅读代码时可能不得不在两个地方跳转查看其实现（虽然标识符是语义化的，但不能提供实现的细节）。

BTW，在模板中直接使用函数只是类似于使用匿名函数的编码风格。

2024-06-14 05:40 UTC, jiaojiaodubai commented
> > 我觉得有一些更改违背了初始的意图
> 
> 比如？

`useSortedItemTypes` 旨在按照界面语言的顺序进行排序，以便页面上的显示条目类型顺序对于用户而言具有一定的规律性，而现在根据原始的变量名称进行排序则失去了这个意义，不如不sort。

2024-06-14 05:47 UTC, jiaojiaodubai commented on src/translators/data/translatorsLittle.data.ts
> +export { data };
在具有隐式导出的前提下，这样创建是为了做类型注解吗？但即使在原来有这个注解的情况下，我的编辑器似乎也没有在子模块中对 `data` 进行补全提示和类型提示。

2024-06-14 07:57 UTC, northword commented
emmm 好像搞错了 :(

2024-06-14 07:59 UTC, northword commented
1

2024-06-14 08:02 UTC, northword commented on src/translators/data/translatorsLittle.data.ts
> +export { data };
我这边添加后才是正常的，不添加会报错。

![image](https://github.com/zotero-chinese/website/assets/44738481/e9f026c2-1561-4f2e-9cf1-26364f16a218)

2024-06-14 08:10 UTC, northword commented on src/translators/components/TranslatorCard.vue
> +            type="info"
这里有一个来自 GPT 的回答：https://chatgpt.com/share/e6444ab6-fbc7-47ab-bf69-f074d1821a2a

2024-06-14 08:12 UTC, northword commented
> useSortedItemTypes 旨在按照界面语言的顺序进行排序，以便页面上的显示条目类型顺序对于用户而言具有一定的规律性，而现在根据原始的变量名称进行排序则失去了这个意义，不如不sort。

emm，这个是我理解错了，我理解成了仅把 “多个条目” 放在最后。

2024-06-14 08:17 UTC, northword commented
reopen

2024-06-14 08:21 UTC, jiaojiaodubai commented on src/translators/data/translatorsLittle.data.ts
> +export { data };
VitePress官方文档的例子中也没有导出，我感觉是通用语法检查器给的报错，我记得你在 plugin 的组件里是直接给注释掉的

2024-06-14 08:53 UTC, jiaojiaodubai commented
我目前的意见：

- 常数可以分离到 script
- 恢复 tag 的字面排序（如果你钟爱使用原始数据来判断，可能需要额外的处理）
- 类型检查需要统一一下是注释抑制住还是导出带注解的常量

2024-06-14 08:54 UTC, northword commented on src/translators/data/translatorsLittle.data.ts
> +export { data };
vitepress 官方例子是 js 的，对于 ts：https://vitepress.dev/zh/guide/data-loading#typed-data-loaders

2024-06-14 09:07 UTC, northword commented
> 恢复 tag 的字面排序（如果你钟爱使用原始数据来判断，可能需要额外的处理）

已恢复

> 类型检查需要统一一下是注释抑制住还是导出带注解的常量

统一导出带注解的，plugins 那边是带注解了的，charts 没有，因为那个数据结构是 volatile-static 在写，我还没改到；另外一个没有注解的是 updateTime，这就只是一个 string，可有可无。

2024-06-14 09:22 UTC, jiaojiaodubai commented
我没有疑问了，我想在 translator 页面实现的功能已经落实。

受长期以来大量错误信息的影响，许多用户形成了一种错误认识，认为 Connector 是一个 Zotero 插件，或者认为 Connector 抓取元数据的功能由茉莉花完成。我认为有必要在百科全书的相关章节（如“添加条目”）提到这一页面，说清这个页面的作用。

2024-06-14 09:25 UTC, northword commented
> 受长期以来大量错误信息的影响，许多用户形成了一种错误认识，认为 Connector 是一个 Zotero 插件，或者认为 Connector 抓取元数据的功能由茉莉花完成。我认为有必要在百科全书的相关章节（如“添加条目”）提到这一页面，说清这个页面的作用。

这个可以有！

translator 页面是否也需要添加一个简短的描述呢？或者是加个转到这个章节的链接（可以在相关内容完成后）

2024-06-14 09:49 UTC, merged